#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: inCycling.gr

# Short bio or description (displayed in the header)
description: inCycling.gr - Blog 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatarfiles.alphacoders.com/383/38368.jpg

# File encoding
encoding: utf-8

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@incycling.gr
  facebook: InCycling-343369849397124
  flickr:
  github: 
  instagram: evangelos_kastamoulas
  linkedin: evangelos-kastamoulas-a0641646
  pinterest:
  rss: 
  twitter: EKastas
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: 101107517353642507070


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: incycling-gr-1

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-93460817-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.incycling.gr

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown 
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
